name: Smoke test
on: [push, pull_request]
jobs:
  smoke:
    runs-on: ubuntu-latest
    steps:
      - name: Probe homepage
        run: |
          curl -sI https://<contractors-page>.netlify.app/ | grep -E "200|Netlify"
          curl -sI https://<contractors-page>.netlify.app/assets/css/site.css?v=1 | grep "text/css"
